server:
  port: 8081
#配置数据源的属性
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/rent005?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: root
      ##设置最大连接数
      max-active: 20
      ##设置等待时间
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
   #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        ##白名单
        allow:
        ##黑名单
        deny: 
        url-pattern: /druid/*
  #thymeleaf的配置 
  thymeleaf: 
    cache: false
    enabled: true
#      web-stat-filter: 
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#配置mybatisplus
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 3
  anon-urls:
  - /index.html*
  - /rent/login*
  - /rent/register*
  - /rent/forget*
  - /user/addUser
  - /login/login*
  ##注意添加验证码过滤 ┭┮﹏┭┮
  - /login/getCode
  - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
  - /**